version: '3.7'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
        - ${POSTGRES_PORT}:5432
    volumes:
      - ~/seshat/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    ports:
      - ${REDIS_PORT}:6379
